#!/bin/bash

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.rs$") || true)
if [ ! -z "${files}" ]; then
	cargo +nightly fmt
	while IFS= read -r file; do
		git add "$file"
	done <<< "$files"
fi
